---
- name: Gather and store facts from remote server
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather facts from remote server
      ansible.builtin.setup:
      register: facts_result

    - name: Save facts to a file named after the server
      ansible.builtin.template:
        src: ../templates/facts_template.j2
        dest: "/home/user/facts2/{{ ansible_hostname }}_facts.txt"
      delegate_to: localhost